name: "Install & Setup Theos"
description: "Use Theos in your GitHub Actions to build iOS tweaks"
author: "waruhachi"
branding:
  icon: dollar-sign
  color: purple

inputs:
  theos-dir:
    description: "Directory to install Theos to"
    required: false
    default: "~/theos"
  theos-src:
    description: "What repo to clone Theos from"
    required: false
    default: "theos/theos"
  theos-branch:
    description: "What branch to clone Theos from"
    required: false
    default: "master"
  theos-cache:
    description: "Cache Theos"
    required: false
    default: "true"
  sdks:
    description: "Install a custom SDK"
    required: false
    default: "false"
  sdks-src:
    description: "What repo to clone the custom SDK from"
    required: false
    default: "theos/sdks"
  libgcuniversal:
    description: "Install LibGcUniversal"
    required: false
    default: "false"
  libgcuniversal-src:
    description: "What repo to clone LibGcUniversal from"
    required: false
    default: "MrGcGamer/LibGcUniversalDocumentation"
  altlist:
    description: "Install AltList"
    required: false
    default: "false"
  altlist-src:
    description: "What repo to clone AltList from"
    required: false
    default: "opa334/AltList"

runs:
  using: "composite"
  steps:
    - name: Generate Cache Key
      id: cache-key
      shell: bash
      run: |
        echo "theos-cache-key=$(/bin/date -u "+%Y%m%d%H")" >> $GITHUB_OUTPUT

    - name: Install dependencies
      shell: bash
      run: |
        brew list xz >/dev/null 2>&1 || brew install xz
        brew list make >/dev/null 2>&1 || brew install make
        brew list ldid >/dev/null 2>&1 || brew install ldid
        echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH
        echo PATH=\"$(brew --prefix make)/libexec/gnubin:\$PATH\" >> ~/.bash_profile

    - name: Theos Cache
      id: theos-cache
      uses: actions/cache@v4
      if: inputs.theos-cache == 'true'
      with:
        path: ${{ inputs.theos-dir }}
        key: ${{ inputs.theos-src }}-${{ inputs.theos-branch }}-${{ steps.cache-key.outputs.theos-cache-key }}

    - name: Setup Theos
      if: inputs.theos-cache != 'true' || steps.theos-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        set -e
        if [[ "${{ inputs.sdks }}" == "true" ]]; then
          export SDK_FETCH_URL="https://api.github.com/repos/${{ inputs.sdks-src }}/releases/latest"
        fi
        bash -c "$(curl -fsSL https://raw.githubusercontent.com/${{ inputs.theos-src }}/${{ inputs.theos-branch }}/bin/install-theos)"

        export THEOS=${{ inputs.theos-dir }}

        if [[ "${{ inputs.libgcuniversal }}" == "true" ]]; then
          git clone https://github.com/${{ inputs.libgcuniversal-src }}.git
          cd $(basename "${{ inputs.libgcuniversal-src }}")
          ./install.sh
          cd ..
        fi

        if [[ "${{ inputs.altlist }}" == "true" ]]; then
          git clone https://github.com/${{ inputs.altlist-src }}.git
          cd $(basename "${{ inputs.altlist-src }}")
          ./install_to_theos.sh
          cd ..
        fi

    - name: Update Theos
      if: inputs.theos-cache == 'true' && steps.theos-cache.outputs.cache-hit == 'true'
      shell: bash
      run: |
        export THEOS=${{ inputs.theos-dir }}
        $THEOS/bin/update-theos
