name: "Install & Setup Theos"
description: "Use Theos in your GitHub Actions to build iOS tweaks"
author: "waruhachi"
branding:
  icon: dollar-sign
  color: purple

inputs:
  theos-dir:
    description: "Directory to install Theos to"
    required: false
    default: "~/theos"
  theos-src:
    description: "What repo to clone Theos from"
    required: false
    default: "theos/theos"
  theos-branch:
    description: "What branch to clone Theos from"
    required: false
    default: "master"
  theos-cache:
    description: "Cache Theos"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Get Current Hour
      id: cache-key
      shell: bash
      run: |
        echo "hour=$(/bin/date -u "+%H")" >> $GITHUB_OUTPUT

    - name: Install dependencies
      shell: bash
      run: |
        brew list xz >/dev/null 2>&1 || brew install xz
        brew list make >/dev/null 2>&1 || brew install make
        brew list ldid >/dev/null 2>&1 || brew install ldid

    - name: Theos Cache
      id: theos-cache
      uses: actions/cache@v4
      if: inputs.theos-cache == 'true'
      with:
        path: ${{ inputs.theos-dir }}
        key: ${{ inputs.theos-src }}-${{ inputs.theos-branch }}-${{ steps.cache-key.outputs.hour }}

    - name: Install Theos
      if: inputs.theos-cache != 'true' || steps.theos-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH
        bash -c "$(curl -fsSL https://raw.githubusercontent.com/${{ inputs.theos-src }}/${{ inputs.theos-branch }}/bin/install-theos)"
        echo "THEOS=${{ inputs.theos-dir }}" >> $GITHUB_ENV

    - name: Update Theos
      if: inputs.theos-cache == 'true' && steps.theos-cache.outputs.cache-hit == 'true'
      shell: bash
      run: |
        echo "THEOS=${{ inputs.theos-dir }}" >> $GITHUB_ENV
        export THEOS=${{ inputs.theos-dir }}
        $THEOS/bin/update-theos
